# Database Configuration
db.url=jdbc:mysql://localhost:3306/code_analyzer
db.user=root
db.pass=Buingocanh@234

# AI Configuration
ai.api.key=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
ai.api.url=https://api.groq.com/openai/v1/chat/completions

# Crawler Settings
crawl.delay.ms=3000
crawl.periodic.hours=24
