# Database Configuration
db.url=jdbc:mysql://localhost:3306/code_analyzer
db.user=root
db.pass=Buingocanh@234

# AI Configuration
ai.api.key=AIzaSyDfMaiT-H4anHoHwtHVcS2UQlNCftwmMOw
ai.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

# Crawler Settings
crawl.delay.ms=3000
crawl.periodic.hours=24
